# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f78d92c35247bf3b258f298bb4f74f3aa40372fb3c83a479d99096274c0e1f5a56a7dd1c01d90637d8b44bc657b8b0eb6c4744498503b01e0bc65c9e7cd70b8

test:
  secret_key_base: ef3aad7de830cd350b52807359623469cea7dc92360b0f51b1438c3f2a8179344666478d8e33b8bad7994a5cfb37bb949e321eb8ffb8fe515318f3d05576143d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
